version: '3'

volumes:
    nextcloud_db:

services:
    db:
        image: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
        restart: always
        volumes:
          - nextcloud_db:/var/lib/mysql
        env_file:
          - variables.env
        networks:
            backend:
    
    app:
        image: thelastbilly/nextcloud:latest
        build: .
        container_name: nextcloud
        links:
            - db
        volumes:
            - ./installations:/installations
            - /mnt/main/Vault/nextcloud:/data
            - ./config:/config
        networks:
            backend:
            hoster:
                ipv4_address: 10.30.30.23
        restart: always
        env_file:
          - variables.env
networks:
    hoster:
        external: true
    backend:
