version: '3'

volumes:
    nextcloud_db:
    nextcloud_install:
    nextcloud_data:
    nextcloud_config:

services:
    db:
        image: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
          - nextcloud_db:/var/lib/mysql
        env_file:
          - variables.env
    
    app:
        image: thelastbilly/nextcloud:latest
        build: .
        links:
            - db
        volumes:
            - nextcloud_install:/installations
            - nextcloud_data:/data
            - nextcloud_config:/config
        ports:
            - "8080:80"
        restart: always
        env_file:
          - variables.env
